{{- if .Values.gatewayClass.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.controller.gatewayClassName }}
  labels:
    {{- include "pingora-gw-ctrl.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.controller.controllerName }}
  {{- if .Values.pingoraConfig.create }}
  parametersRef:
    group: pingora.k8s.lex.la
    kind: PingoraConfig
    name: {{ .Values.pingoraConfig.name | default (include "pingora-gw-ctrl.fullname" .) }}
  {{- end }}
{{- end }}
