{{- if .Values.gatewayClass.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.controller.gatewayClassName }}
  labels:
    {{- include "pingora-gw-ctrl.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.controller.controllerName }}
  {{- if .Values.gatewayClassConfig.create }}
  parametersRef:
    group: cf.k8s.lex.la
    kind: GatewayClassConfig
    name: {{ .Values.gatewayClassConfig.name | default (include "pingora-gw-ctrl.fullname" .) }}
  {{- end }}
{{- end }}
