annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: BSD-3-Clause
  artifacthub.io/links: |
    - name: Chart Repository
      url: https://github.com/lexfrei/pingora-gateway-controller/
    - name: Gateway API
      url: https://gateway-api.sigs.k8s.io/
    - name: Pingora
      url: https://github.com/cloudflare/pingora
  artifacthub.io/signKey: |
    fingerprint: keyless
    url: https://github.com/lexfrei/pingora-gateway-controller/.github/workflows/release.yaml@refs/heads/master
apiVersion: v2
name: pingora-gateway-controller
description: Kubernetes Gateway API controller for Pingora proxy
type: application
version: "0.1.0"
kubeVersion: ">=1.25.0-0"
appVersion: "0.0.1"
icon: https://avatars.githubusercontent.com/u/314135
home: https://github.com/lexfrei/pingora-gateway-controller/
keywords:
  - pingora
  - gateway-api
  - proxy
  - kubernetes
  - controller
  - networking
  - rust
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
sources:
  - https://github.com/lexfrei/pingora-gateway-controller/
